#!/usr/bin/env bash

docker-compose up -d --build

#docker-compose exec kafka kafka-configs --zookeeper zookeeper:2181 --alter --add-config 'SCRAM-SHA-256=[password=kafka],SCRAM-SHA-512=[password=kafka]' --entity-type users --entity-name kafka

#docker-compose exec kafka kafka-configs --zookeeper zookeeper:2181 --alter --add-config 'SCRAM-SHA-256=[password=alice-secret],SCRAM-SHA-512=[password=alice-secret]' --entity-type users --entity-name alice
#docker-compose exec kafka kafka-configs --zookeeper zookeeper:2181 --alter --add-config 'SCRAM-SHA-256=[password=bob-secret],SCRAM-SHA-512=[password=bob-secret]' --entity-type users --entity-name bob


docker-compose exec kafka kafka-acls --authorizer-properties zookeeper.connect=zookeeper:2181 --add --cluster --operation=All --allow-principal=User:kafka

when I execute 

docker compose exec kafka bash
kafka-configs --bootstrap-server localhost:29093 --entity-type brokers --entity-name 1  \
    --command-config=/etc/kafka/kafka-user.properties \
    --alter \
    --add-config confluent.security.event.router.config=${file:/etc/kafka/auditUpdate.json:router},bootstrap.servers=kafka:29093


kafka-configs --bootstrap-server localhost:29093 --entity-type brokers --entity-name 2  \
    --command-config=/etc/kafka/kafka-user.properties \
    --alter \
    --add-config confluent.security.event.router.config=${file:/etc/kafka/auditUpdate.json:router},bootstrap.servers=kafka2:29093
    
I get the following error


Invalid value com.fasterxml.jackson.core.JsonParseException: Unrecognized token 'destinations': was expecting (JSON String, Number, Array, Object or token 'null', 'true' or 'false')

kafka-configs --bootstrap-server kafka:29093 --command-config=/etc/kafka/kafka-user.properties --entity-type brokers --describe | grep confluent.security.event.router.config | awk -Fconfig= '{print $2}'

kafka-topics --bootstrap-server kafka:29093 --list --command-config /etc/kafka/kafka-user.properties

kafka-topics --bootstrap-server kafka:29093 --describe _confluent-command --command-config /etc/kafka/kafka-user.properties



--------

kafka-configs --bootstrap-server kafka:29093 --command-config=/etc/kafka/kafka-user.properties --entity-type brokers --entity-default --alter --delete-config "confluent.security.event.router.config"

kafka-configs --bootstrap-server kafka:29093 --command-config=/etc/kafka/kafka-user.properties --entity-type brokers --entity-default --describe

--------

kafka-configs --bootstrap-server kafka:29093 --command-config=/etc/kafka/kafka-user.properties --entity-type brokers --entity-default --alter --delete-config confluent.security.event.router.config,bootstrap.servers


--------
docker compose exec kafka bash
kafka-configs --bootstrap-server kafka:29093 --command-config=/etc/kafka/kafka-user.properties --entity-type brokers --entity-default --alter --add-config-file /etc/kafka/new.properties